prefix a-cd: <https://w3id.org/arco/ontology/context-description/>
prefix a-ce: <https://w3id.org/arco/ontology/cultural-event/>
prefix a-dd: <https://w3id.org/arco/ontology/denotative-description/>
prefix lite: <https://w3id.org/arco/ontology/arco-lite/>
prefix a-loc: <https://w3id.org/arco/ontology/location/>
prefix arco: <https://w3id.org/arco/ontology/arco/>
prefix cis: <http://dati.beniculturali.it/cis/>
prefix clv: <https://w3id.org/italia/onto/CLV/>
prefix core: <https://w3id.org/arco/ontology/core/>
prefix cov: <https://w3id.org/italia/onto/COV/>
prefix cpv: <https://w3id.org/italia/onto/CPV/>
prefix ipac: <https://ipac.cultura.gov.it/onto/ipac/>
prefix l0: <https://w3id.org/italia/onto/l0/>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix ti: <https://w3id.org/italia/onto/TI/>
prefix a-cc: <https://w3id.org/arco/ontology/cataloguing-campaign/>
prefix a-mi: <https://w3id.org/arco/ontology/musical-istrument/>
prefix a-con: <https://w3id.org/arco/ontology/construction-description/>
prefix roapit: <https://w3id.org/italia/onto/RO/>
prefix dcatapit: <http://dati.gov.it/onto/dcatapit/>
prefix a-spe: <https://w3id.org/arco/ontology/natural-specimen-description/>
prefix mu: <https://w3id.org/italia/onto/MU/>
prefix clo: <https://w3id.org/arco/ontology/clothing-description/>

CONSTRUCT { ?entity ipac:shareable "true"^^xsd:boolean }
WHERE {
VALUES ?shareableClass
	{
	a-cd:Edition
	a-ce:RecurrentSituationSeries
	a-con:Construction
	a-con:OutdoorSpace
	a-dd:CulturalPropertyType
	a-mi:MusicalInstrument
	a-spe:Animal
	a-spe:ArtificialSpecimen
	a-spe:Meteorite
	a-spe:Mineral
	a-spe:NaturalSpecimen
	a-spe:Rock
	a-spe:Specimen
	a-spe:Vegetal
	arco:ArchaeologicalProperty
	arco:ArchitecturalOrLandscapeHeritage
	arco:BotanicalHeritage
	arco:CulturalProperty
	arco:DemoEthnoAnthropologicalHeritage
	arco:HistoricOrArtisticProperty
	arco:ImmovableCulturalProperty
	arco:IntangibleCulturalProperty
	arco:MineralHeritage
	arco:MovableCulturalProperty
	arco:MusicalHeritage
	arco:MusicHeritage
	arco:NaturalHeritage
	arco:NumismaticProperty
	arco:PalaeontologicalHeritage
	arco:PetrologicHeritage
	arco:PhotographicHeritage
	arco:PhysicalAnthropologyHeritage
	arco:PlanetaryScienceHeritage
	arco:ScientificOrTechnologicalHeritage
	arco:ZoologicalHeritage
	cis:CulturalEntity
	cis:CulturalInstituteOrSite
	cis:Site
	clo:Clothing
	clv:Building
	cpv:Person
	dcatapit:Organization
	l0:Agent
	l0:EventOrSituation
	a-cat:PrivacyReason
	a-cd:AccessoryType
	a-cd:AcquisitionType
	a-cd:Age
	a-cd:ArchaeologicalExcavation
	a-cd:ArchaeologicalFieldSurvey
	a-cd:ArchaeometricDiagnosticSurveyType
	a-cd:ArchivalFonds
	a-cd:ArchivalResourceType
	a-cd:ArchivalSeries
	a-cd:ArchivalSubseries
	a-cd:AttributionMotivation
	a-cd:AudioCollection
	a-cd:BibliographyCategory
	a-cd:BibliographyType
	a-cd:BiologicalTaxon
	a-cd:CertificationType
	a-cd:ChangeOfAvailabilityType
	a-cd:Circumstance
	a-cd:CollectionMembership
	a-cd:CulturalPropertyStage
	a-cd:CulturalScope
	a-cd:DerivatedWorkType
	a-cd:DesignationInTime
	a-cd:DesignationType
	a-cd:DetectionMethod
	a-cd:DocumentationCategory
	a-cd:DocumentationType
	a-cd:EligibleIntervention
	a-cd:ExportImportCertificationType
	a-cd:FilmDocumentation
	a-cd:FindingContextType
	a-cd:FluidDynamism
	a-cd:InterpretationCriterion
	a-cd:InterventionType
	a-cd:Inventory
	a-cd:InventoryType
	a-cd:LaboratoryTestType
	a-cd:LegalSituation
	a-cd:LegalSituationType
	a-cd:License
	a-cd:NumismaticSeries
	a-cd:ObservationSurveyType
	a-cd:PhotographicDocumentation
	a-cd:PhysicalCharacteristic
	a-cd:PrintingPlatesSeries
	a-cd:Profession
	a-cd:Publication
	a-cd:RecordingType
	a-cd:ReferenceCatalogue
	a-cd:RelatedWorkSituation
	a-cd:RelationshipType
	a-cd:Rock
	a-cd:Scale
	a-cd:SECCategory
	a-cd:Sex
	a-cd:SourceAndDocument
	a-cd:Species
	a-cd:StorageMediumType
	a-cd:StratigraphicUnit
	a-cd:Subject
	a-cd:SubjectDiscipline
	a-cd:Subspecies
	a-cd:SurveyMethod
	a-cd:SurveyMotivation
	a-cd:SurveyType
	a-cd:ThematicPath
	a-cd:ThematicPathType
	a-cd:Title
	a-cd:Tomb
	a-cd:UrbanPlanningInstrumentType
	a-cd:Use
	a-cd:UseFunction
	a-cd:UserSocialCategory
	a-cd:UseType
	a-cd:VideoCollection
	a-ce:Acknowledgement
	a-ce:Competition
	a-ce:RecurrentTimePeriod
	a-con:ConnectionElementType
	a-con:Floor
	a-con:FlooringLayout
	a-con:FlooringType
	a-con:FoundationType
	a-con:HorizontalElementType
	a-con:Layout
	a-con:PlanLayout
	a-con:PositionOnGroundLevelType
	a-con:RoofingType
	a-con:RoofStructure
	a-con:RoofType
	a-con:Stairs
	a-con:VerticalElementType
	a-con:WaterElementType
	a-dd:a-dd:AgeRange
	a-dd:AffixedElementType
	a-dd:AnomalyClassification
	a-dd:Arrangement
	a-dd:BandageType
	a-dd:ConservationMethod
	a-dd:ConservationStatusType
	a-dd:CulturalPropertyAccessibility
	a-dd:CulturalPropertyDefinition
	a-dd:CulturalPropertySpecification
	a-dd:Filigree
	a-dd:FontStyle
	a-dd:Format
	a-dd:FunctionalPurpose
	a-dd:IconographicOrDecorativeApparatusType
	a-dd:ImplementationMethod
	a-dd:Legibility
	a-dd:Measurement
	a-dd:MeasurementCollection
	a-dd:Orientation
	a-dd:OrnamentalMotif
	a-dd:SampleType
	a-dd:Software
	a-dd:SortingCriterion
	a-dd:Support
	a-dd:TechnicalCharacteristic
	a-dd:WritingSystem
	a-loc:BaseMap
	a-loc:CadastralFolio
	a-loc:CadastralSubordinate
	a-loc:CadastralUnitCollection
	a-loc:Chronozone
	a-loc:Continent
	a-loc:CulturalInstituteOrSiteDefinition
	a-loc:CulturalInstituteOrSiteSpecification
	a-loc:CulturalInstituteOrSiteType
	a-loc:Eonothem
	a-loc:Erathem
	a-loc:GeologicalMap
	a-loc:GeometryMethod
	a-loc:GeometryTechnique
	a-loc:Incline
	a-loc:LanduseMap
	a-loc:LithostratigraphicBed
	a-loc:LithostratigraphicComplex
	a-loc:LithostratigraphicFormation
	a-loc:LithostratigraphicGroup
	a-loc:LithostratigraphicMember
	a-loc:LithostratigraphicStratum
	a-loc:LithostratigraphicSupergroup
	a-loc:LocationType
	a-loc:NaturalEnvironmentType
	a-loc:OldTown
	a-loc:OutcropType
	a-loc:PedologicalMap
	a-loc:ShadeTolerance
	a-loc:SiteDefinition
	a-loc:SiteSpecification
	a-loc:SiteType
	a-loc:Substrate
	a-loc:SubstrateType
	a-loc:ToponymInTime
	a-loc:UrbanArea
	a-loc:ZoogeographicRegion
	a-loc:Cadastre
	a-mi:MusicalInstrumentTaxon
	a-mi:MusicalNote
	a-spe:AlterationGrade
	a-spe:AlterationType
	a-spe:BiogenicSedimentaryStructure
	a-spe:BiologicalSubspecies
	a-spe:BotanicalForm
	a-spe:Cement
	a-spe:Chondrule
	a-spe:ChondruleType
	a-spe:ChronostratigraphicSeries
	a-spe:ChronostratigraphicStage
	a-spe:ChronostratigraphicSubstage
	a-spe:ChronostratigraphicSystem
	a-spe:CloseIndividual
	a-spe:ContactType
	a-spe:CrystallographicCharacteristic
	a-spe:Cultivar
	a-spe:DevelopmentStage
	a-spe:EmpiricalChemicalFormula
	a-spe:EruptiveType
	a-spe:Family
	a-spe:Fossil
	a-spe:HarvestingMethod
	a-spe:HarvestingMotivation
	a-spe:HostIndividual
	a-spe:HostRock
	a-spe:Inclusion
	a-spe:LithologicType
	a-spe:MainMass
	a-spe:Matrix
	a-spe:MineralClass
	a-spe:MineralDepositType
	a-spe:MineralSubclass
	a-spe:PlanetologicClass
	a-spe:PlanetologicGenus
	a-spe:PlanetologicGroup
	a-spe:PlanetologicSpecies
	a-spe:PreparationType
	a-spe:PreservationType
	a-spe:PrimarySedimentaryStructure
	a-spe:SecondarySedimentaryStructure
	a-spe:SedimentaryStructure
	a-spe:SimplifiedChemicalFormula
	a-spe:SpecimenCollection
	a-spe:TextureType
	a-spe:TypeOfTypeSpecimen
	a-spe:Typification
	a-spe:Variety
	a-spe:WeatheringGrade
	arco:ArchaeologicalMaterial
	arco:ArchaeologicalMaterialCategory
	arco:ClassificationSystem
	arco:CulturalPropertyCataloguingCategory
	arco:CulturalPropertyCategory
	arco:CulturalPropertyInventoryCategory
	arco:NumismaticPropertyFunctionalCategory
	arco:NumismaticPropertyTypologicalCategory
	arco:PalaeontologicalHeritage
	arco:PetrologicHeritage
	arco:PhotographicHeritageClassificationType
	arco:ReferenceCoinLegend
	cis:CISNameInTime
	cis:ClericalAdministrativeArea
	cis:CollectionCulEnt
	cis:CulturalEvent
	cis:GeographicalFeature
	cis:MonumentalArea
	clo:FastenerType
	clo:InteriorElementType
	clo:NeckType
	clo:PocketType
	clo:SleeveType
	clv:Address
	clv:AddressArea
	clv:AdminUnitComponent
	clv:City
	clv:Country
	clv:District
	clv:Feature
	clv:GeometryType
	clv:Province
	clv:Region
	core:AgentRole
	core:Depiction
	core:Event
	cov:Group
	dc:Language
	a-cc:ActivityStatus
	a-cc:Application
	a-cc:ArchivalCollection
	a-cc:OrganizationType
	a-cc:Protocol
	a-cc:CampaignStatus
	a-cc:CampaignType
	a-cc:CatalogueNumberAssignment
	a-cc:CataloguingActivity
	a-cc:CataloguingLevel
	a-cc:CataloguingOrDigitizationCampaign
	a-mi:HornbostelSachsClass
	l0:Concept
	l0:Object
	mu:MeasurementUnit
	mu:Value
	roapit:Role
	tiapit:TimeInterval
	}
?entity a ?shareableClass.
}

