prefix a-cd: <https://w3id.org/arco/ontology/context-description/>
prefix a-ce: <https://w3id.org/arco/ontology/cultural-event/>
prefix a-dd: <https://w3id.org/arco/ontology/denotative-description/>
prefix lite: <https://w3id.org/arco/ontology/arco-lite/>
prefix a-loc: <https://w3id.org/arco/ontology/location/>
prefix arco: <https://w3id.org/arco/ontology/arco/>
prefix cis: <http://dati.beniculturali.it/cis/>
prefix clv: <https://w3id.org/italia/onto/CLV/>
prefix core: <https://w3id.org/arco/ontology/core/>
prefix cov: <https://w3id.org/italia/onto/COV/>
prefix cpv: <https://w3id.org/italia/onto/CPV/>
prefix ipac: <https://ipac.cultura.gov.it/onto/ipac/>
prefix l0: <https://w3id.org/italia/onto/l0/>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix ti: <https://w3id.org/italia/onto/TI/>
prefix a-cc: <https://w3id.org/arco/ontology/cataloguing-campaign/>
prefix a-mi: <https://w3id.org/arco/ontology/musical-istrument/>
prefix a-con: <https://w3id.org/arco/ontology/construction-description/>
prefix roapit: <https://w3id.org/italia/onto/RO/>
prefix dcatapit: <http://dati.gov.it/onto/dcatapit/>
prefix a-spe: <https://w3id.org/arco/ontology/natural-specimen-description/>
prefix mu: <https://w3id.org/italia/onto/MU/>
prefix clo: <https://w3id.org/arco/ontology/clothing-description/>

CONSTRUCT { ?entity ipac:shareable "false"^^xsd:boolean }
WHERE {
VALUES ?nonshareableClass
	{
 	a-spe:Accession
	a-dd:Accessory
	a-cat:AccessProfile
	a-cd:Acquisition
	a-dd:AffixedElement
	a-cd:Age
	a-cd:AgeInterpretation
	core:AgentRole
	a-cd:AgeOfDeathInterpretation
	a-cd:AlternativeAuthorshipAttribution
	a-cat:AlternativeIdentifier
	a-loc:Altitude
	a-cd:Anomaly
	a-cd:ArchaeologicalExcavation
	a-cd:ArchaeologicalFieldSurvey
	arco:ArchaeologicalMaterial
	a-cd:ArchaeometricDiagnosticSurvey
	a-cd:ArchivalRecordSetMembership
	a-cd:AudioDocumentation
	a-cd:AudioRecording
	a-dd:Bandage
	a-loc:BaseMap
	a-cd:Bibliography
	a-loc:CadastralFolio
	a-loc:CadastralIdentity
	a-loc:CadastralUnitCollection
	a-cat:CatalogueRecordVersion
	a-cd:Certification
	a-cd:ChangeOfAvailability
	a-spe:ChondrulePresence
	a-cd:Circumstance
	core:ClassificationInTime
	a-spe:Cleavage
	a-dd:ClimateSituation
	a-dd:CoinDesign
	a-cd:CoinIssuance
	a-dd:CoinLegend
	a-cd:CollectionMembership
	a-cd:Commission
	a-dd:CommunicationMedium
	a-con:ConnectionElement
	a-cd:ConservationIntervention
	a-dd:ConservationStatus
	a-con:Construction
	a-con:ConstructionElement
	a-loc:Coordinates
	a-cd:Copy
	a-cd:Copyright
	a-dd:Counterstamp
	a-spe:CrystalHabit
	a-spe:CrystalMorphology
	a-spe:CrystalTwinning
	clo:Cuff
	cis:CulturalEntity
	a-dd:CulturalEntityTechnicalStatus
	arco:CulturalPropertyPart
	a-cat:CulturalPropertyRecord
	a-cd:CulturalScopeAttribution
	a-cd:Dating
	a-dd:DecorativeApparatus
	a-dd:Dedication
	a-cd:DerivatedWork
	a-dd:Design
	a-cd:DesignationInTime
	a-cd:Documentation
	a-cd:Edition
	a-loc:EnvironmentalDamage
	a-cd:Estimate
	core:Event
	a-cd:ExportImportCertification
	a-con:Facade
	a-cd:Facsimile
	a-cd:FairMarketCircumstance
	clo:Fastener
	a-cd:FilmDocumentation
	a-cd:FinalWork
	a-cd:FindingContext
	a-con:Floor
	a-con:Flooring
	a-cd:Forgery
	a-con:Foundation
	a-cd:Fruition
	a-spe:FruitSample
	a-loc:GeologicalContext
	clv:Geometry
	a-spe:Grains
	a-cd:GraphicOrCartographicDocumentation
	a-con:HorizontalElement
	a-con:HorizontalSubdivision
	a-dd:IconographicOrDecorativeApparatus
	a-spe:IdentificationInTime
	clv:Identifier
	a-dd:Inscription
	a-cd:Inspection
	clo:InteriorElement
	a-cd:Intervention
	a-cd:InventorySituation
	a-cd:LaboratoryTest
	a-con:Layout
	a-cd:LegalSituation
	a-cd:LifeCycleCircumstance
	a-dd:Measurement
	a-dd:MeasurementCollection
	a-loc:MineralDeposit
	a-spe:MineralPresence
	a-cd:MultimediaDocumentation
	a-loc:NaturalEnvironment
	clo:Neck
	a-loc:NeighbouringCadastralEntity
	a-cd:NumismaticSeriesMembership
	l0:Object
	a-cd:ObservationSurvey
	a-con:OpenSpace
	a-loc:Outcrop
	a-cd:PaleopathologySurvey
	a-spe:Paramorphosis
	a-cd:PhotographicDocumentation
	arco:PhotographicHeritageClassification
	a-cd:PhotographicRecording
	a-cd:PhotographicSeriesMembership
	a-cd:PhotographicSubseriesMembership
	a-cd:PhotoInterpretationRendering
	clo:Pocket
	a-spe:PollenSample
	a-con:PositionOnGroundLevel
	a-cd:PreferredAuthorshipAttribution
	a-spe:Preparation
	a-cd:PreparatoryOrFinalWork
	a-cd:PreparatoryWork
	a-cd:PrintingPlatesSeries
	a-cd:PrintInPublication
	a-cd:ProductionCycleCircumstance
	a-cd:ProtectiveMeasure
	a-cat:Pseudomorphosis
	a-cd:Publication
	a-cat:Record
	a-ce:RecurrentSituationSeries
	a-cd:ReferenceCatalogue
	a-spe:Reflectance
	a-spe:Refraction
	a-cd:RelatedWorkSituation
	a-cd:Research
	a-cd:Responsibility
	a-cd:Reuse
	arco:RFid
	a-con:Roof
	a-con:Roofing
	a-cd:SameAuthorCopy
	a-dd:Sample
	a-cd:SeasonCycleCircumstance
	a-spe:SeedSample
	a-cd:Sex
	a-cd:SexInterpretation
	clo:Sleeve
	a-cd:SocialInteractionCircumstance
	a-loc:Soil
	a-cd:SourceAndDocument
	a-spe:SpecimenHarvesting
	a-con:Stairs
	a-cd:StorageMedium
	a-loc:Stratum
	a-mi:String
	a-con:StructuralElement
	a-cd:Subject
	a-dd:Support
	a-cd:Survey
	a-cd:SurveyImage
	a-dd:TechnicalStatus
	a-con:TechnicalSystem
	a-spe:Texture
	roapit:TimeIndexedRole
	a-loc:TimeIndexedTypedLocation
	a-cd:Title
	a-spe:Typification
	a-spe:UnitCell
	a-cd:UrbanPlanningInstrument
	a-cd:Use
	a-con:VerticalElement
	a-con:VerticalSubdivision
	a-cd:VideoRecording
	a-con:WaterElement
	a-con:WaterSystem
	a-spe:WoodSample
	a-cd:WorkCircumstance
	a-cd:YearCycleCircumstance
	a-cd:Copyright
	core:Identifier
	}
?entity a ?nonshareableClass.
}



